import 'other.n'

fn main() {
    var p = other.person_t{
        name = 'hualaka',
        age = 23,
        sex = true,
    }

    [other.person_t] list = [p]

    println(list[0].name, list[0].age, list[0].sex)
    println(p.name, p.age, p.sex)

    p.set_age(30)
    println(p.get_name())
    println(list[0].name, list[0].age, list[0].sex, p.name, p.age, p.sex)

    p.test_self()


    // raw_ptr struct test
    raw_ptr<other.person_t> b = &p
    b.age = 32
    println(b.name, b.age, b.sex)

    b = null
    var c = b.name catch err {
        println(err.msg())
    }

    // 没有完整的 try catch, 所以无法 catch
    b.name = 'hello'
}